spring.application.name=order-service
server.port=8083

spring.datasource.url=${ORDER_DB_URL:jdbc:postgresql://localhost:5432/order_db}
spring.datasource.username=${ORDER_DB_USERNAME:postgres}
spring.datasource.password=${ORDER_DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

product.service.url=${PRODUCT_SERVICE_URL:http://localhost:8082}
