spring.application.name=product-service
server.port=8082

spring.datasource.url=${PRODUCT_DB_URL:jdbc:postgresql://localhost:5432/product_db}
spring.datasource.username=${PRODUCT_DB_USERNAME:postgres}
spring.datasource.password=${PRODUCT_DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
